Clean up install scripts a bit
Issue: #437

diff --git a/install/debian/postinst b/install/debian/postinst
--- a/install/debian/postinst
+++ b/install/debian/postinst
@@ -17,35 +17,38 @@ set -e
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+install_andlogview() {
+  DESKTOP_COMMANDS_INSTALL
+
+  # Add icons to the system icons
+  XDG_ICON_RESOURCE="`command -v xdg-icon-resource 2> /dev/null || true`"
+  if [ ! -x "$XDG_ICON_RESOURCE" ]; then
+    echo "Error: Could not find xdg-icon-resource" >&2
+    exit 1
+  fi
+
+  for icon in andlogview.16.png andlogview.24.png andlogview.png andlogview.48.png andlogview.64.png andlogview.128.png andlogview.256.png; do
+    size="$(echo ${icon} | sed 's/[^0-9]//g')"
+    size=${size:-32}
+    "$XDG_ICON_RESOURCE" install --size "${size}" "/opt/APPLICATION_PACKAGE/lib/${icon}" "name.mlopatkin-andlogview"
+  done
+
+  cp /opt/APPLICATION_PACKAGE/lib/andlogview.svg /usr/share/icons/hicolor/scalable/apps/name.mlopatkin-andlogview.svg
+
+  UPDATE_MENUS="`command -v update-menus 2> /dev/null || true`"
+  if [ -x "$UPDATE_MENUS" ]; then
+    update-menus
+  fi
+
+  # Update cache of .desktop file MIME types. Non-fatal since it's just a cache.
+  update-desktop-database > /dev/null 2>&1 || true
+
+  ln -s /opt/APPLICATION_PACKAGE/bin/APPLICATION_PACKAGE /usr/bin/APPLICATION_PACKAGE
+}
 
 case "$1" in
     configure)
-DESKTOP_COMMANDS_INSTALL
-
-# Add icons to the system icons
-XDG_ICON_RESOURCE="`command -v xdg-icon-resource 2> /dev/null || true`"
-if [ ! -x "$XDG_ICON_RESOURCE" ]; then
-  echo "Error: Could not find xdg-icon-resource" >&2
-  exit 1
-fi
-
-for icon in andlogview.16.png andlogview.24.png andlogview.png andlogview.48.png andlogview.64.png andlogview.128.png andlogview.256.png; do
-  size="$(echo ${icon} | sed 's/[^0-9]//g')"
-  size=${size:-32}
-  "$XDG_ICON_RESOURCE" install --size "${size}" "/opt/APPLICATION_PACKAGE/lib/${icon}" "name.mlopatkin-andlogview"
-done
-
-cp /opt/APPLICATION_PACKAGE/lib/andlogview.svg /usr/share/icons/hicolor/scalable/apps/name.mlopatkin-andlogview.svg
-
-UPDATE_MENUS="`command -v update-menus 2> /dev/null || true`"
-if [ -x "$UPDATE_MENUS" ]; then
-  update-menus
-fi
-
-# Update cache of .desktop file MIME types. Non-fatal since it's just a cache.
-update-desktop-database > /dev/null 2>&1 || true
-
-ln -s /opt/APPLICATION_PACKAGE/bin/APPLICATION_PACKAGE /usr/bin/APPLICATION_PACKAGE
+      install_andlogview
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
