Add proper app menu entry to the package
Issue: #437

diff --git a/install/debian/prerm b/install/debian/prerm
--- a/install/debian/prerm
+++ b/install/debian/prerm
@@ -23,7 +23,29 @@ case "$1" in
     remove|upgrade|deconfigure)
 DESKTOP_COMMANDS_UNINSTALL
 
-rm /usr/bin/APPLICATION_PACKAGE
+# Remove icons from the system icons
+XDG_ICON_RESOURCE="`command -v xdg-icon-resource 2> /dev/null || true`"
+if [ ! -x "$XDG_ICON_RESOURCE" ]; then
+  echo "Error: Could not find xdg-icon-resource" >&2
+  exit 1
+fi
+for icon in andlogview.16.png andlogview.24.png andlogview.png andlogview.48.png andlogview.64.png andlogview.128.png andlogview.256.png; do
+  size="$(echo ${icon} | sed 's/[^0-9]//g')"
+  size=${size:-32}
+  "$XDG_ICON_RESOURCE" uninstall --size "${size}" "name.mlopatkin-andlogview"
+done
+
+rm -f /usr/share/icons/hicolor/scalable/apps/name.mlopatkin-andlogview.svg
+
+UPDATE_MENUS="`command -v update-menus 2> /dev/null || true`"
+if [ -x "$UPDATE_MENUS" ]; then
+  update-menus
+fi
+
+# Update cache of .desktop file MIME types. Non-fatal since it's just a cache.
+update-desktop-database > /dev/null 2>&1 || true
+
+rm /usr/bin/APPLICATION_PACKAGE || true
     ;;
 
     failed-upgrade)
